name: Bug report
description: Report a defect in Gait
title: "[bug] "
labels: ["bug", "needs-triage"]
assignees: ["davidahmann"]
body:
  - type: input
    id: gait_version
    attributes:
      label: Gait version
      description: Output of `gait --version`
      placeholder: gait version 1.0.0
    validations:
      required: true
  - type: input
    id: command
    attributes:
      label: Command used
      description: Exact command that produced the issue.
      placeholder: gait gate eval --policy ... --intent ... --json
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Include exact commands and inputs if possible.
    validations:
      required: true
  - type: textarea
    id: json_output
    attributes:
      label: Structured output (`--json`)
      description: Paste the full `--json` output if available.
      render: json
    validations:
      required: true
  - type: textarea
    id: artifacts
    attributes:
      label: Artifact paths (`gait-out/*`)
      description: List relevant local artifact paths (runpack, trace, regress result, junit).
      placeholder: |
        gait-out/runpack_run_demo.zip
        gait-out/trace_delete_prod.json
        gait-out/regress_result.json
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/output
      description: Paste relevant output or attach sanitized files (no secrets).
    validations:
      required: true
