name: Bug report
description: Report a defect in Gait
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Include exact commands and inputs if possible.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/output
      description: Paste relevant output or attach files.
